icress_root/employee_register_app/urls.py
from django.urls import path
from . import views

app_name= 'employee'

urlpatterns=[
    path('',views.LoadEmployee),
    path('employeeDetails/',views.EmployeeDetails),
    path('employee_ID/<pk>',views.EmployeeID,name='employee_ID'),
    path('deleteemployee/<pk>',views.DeleteEmployee,name='deleteemployee'),
    path('updateemployee/<pk>',views.UpdateEmployee,name='updateemployee'),
]

icress_root/icress/urls.py
from django.contrib import admin
from django.urls import path,include
from.import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',views.home),
    path('courses/',include('courses.urls')),
    path('contactus/',views.contact),
    path('aboutus/',views.about_us),
    path('registermp/',views.employee_registration),
    path('studenthp/',include('reg_app.urls')),
    path('login_logout/',views.login_logout),
    path('dtl/',views.dtl),
    path('employee/',include('employee_register_app.urls')),
    path('studentDJF/',include('student_form_app.urls')),
    path('modelformcreate/',include('model_form_app.urls')),
    path('registersign/',include('login_registration_app.urls')),
    path('vijay/',include('VIJAY_app.urls')),
    path('Hotel/',include('Hotel_app.urls'))
]

icress_root/employee_register_app/models.py
from django.db import models

# Create your models here.

class Employee(models.Model):
    eno=models.IntegerField()
    name=models.CharField(max_length=100)
    age=models.IntegerField()
    salary=models.IntegerField()
    address=models.CharField(max_length=100)

icress_root/employee_register_app/views.py
from django.shortcuts import render,redirect
from .models import Employee
# Create your views here.

def LoadEmployee(request):
    employee_list=Employee.objects.all
    emp_dict={
        'employeeFBV' :  employee_list
    }
    return render(request,'employee_register_app/list_emp.html',context=emp_dict)

def EmployeeDetails(request):
    if request.method=='GET':
        return render(request,'employee_register_app/employee_detail.html')
    elif request.method == 'POST':
        eno = request.POST.get('emp_number')
        name = request.POST.get('name')
        age = request.POST.get('age')
        salary = request.POST.get('salary')
        address = request.POST.get('address')
        employee = Employee(eno=eno, name=name, age=age, salary=salary, address=address)
        employee.save()
        return redirect('/employee/')

def EmployeeID(request,pk):
    employee=Employee.objects.get(id=pk)
    emp_dict={
        'employee' : employee
    }
    return render(request,'employee_register_app/employeeID.html',context=emp_dict)

def DeleteEmployee(request,pk):
    emp=Employee.objects.get(id=pk)
    emp.delete()
    return redirect('/employee/')

def UpdateEmployee(request,pk):
    if request.method=='GET':
        employee=Employee.objects.get(id=pk)
        emp_dict={
            'employee' : employee
        }
        return render(request,'employee_register_app/employee_detail.html',context=emp_dict)
    elif request.method=='POST':
        employee=Employee.objects.get(id=pk)
        eno = request.POST.get('emp_number')
        name = request.POST.get('name')
        age = request.POST.get('age')
        salary = request.POST.get('salary')
        address = request.POST.get('address')
        #employee = Employee(eno=eno, name=name, age=age, salary=salary, address=address)
        employee.eno = eno
        employee.name = name
        employee.age = age
        employee.salary = salary
        employee.address = address
        employee.save()
    return redirect('/employee/')

icress_root/templates/employee_register_app/employeeID.html
{% extends 'layout.html' %}
   {% block employee_style %}
<style>
#customers {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #4CAF50;
  color: white;
}

</style>
  {% endblock %}
  {% block title_content %}
  <title>Employee Details</title>
  {% endblock %}

{% block page_content %}
<h1>{{ employee.name }} Details</h1>
<br>
<br>

<table id="customers">
  <tr>
    <th>ID</th>
    <th>Employee ID</th>
    <th>Name</th>
    <th>Age</th>
	<th>Salary</th>
    <th>Address</th>
  </tr>
  <tr>
    <td>{{ employee.id }}</td>
    <td>{{ employee.eno }}</td>
    <td>{{ employee.name }}</td>
    <td>{{ employee.age }}</td>
	<td>{{ employee.salary }}</td>
    <td>{{ employee.address }}</td>
  </tr>
</table>
<br><br>
<a href="/employee/">Go Back List</a> |
<a href="{% url 'employee:deleteemployee' pk=employee.id %}">Delete Employee</a> |
<a href="{% url 'employee:updateemployee' pk=employee.id %}">Update Employee</a>
{% endblock %}

icress_root/templates/employee_register_app/employee_detail.html
{% extends 'layout.html' %}

{% block title_content %}
{% if employee.id %}
    <title>Update Employee</title>
{% else %}
<title>Create Employee</title>
{% endif %}
{% endblock %}

{% block page_content %}
{% if employee.id %}
<h1>Update Employee</h1>
{% else %}
<h1>Create Employee</h1>
{% endif %}
<form class="row g-3" method="POST">
	{% csrf_token %}
	  <div class="row mb-1">
		<label class="col-form-label">Enter Employee ID</label>
		<div class="col-sm-4">
		  <input type="text" name="emp_number" class="form-control form-control-sm" value="{{ employee.id }}">
		</div>
	  </div>
	  <div class="row mb-1">
		<label class="col-form-label">Enter Employee Name</label>
		<div class="col-sm-4">
		  <input type="text" name="name" class="form-control form-control-sm" value="{{ employee.name }}">
		</div>
	  </div>
	  <div class="row mb-1">
		<label class="col-form-label">Enter Employee Age</label>
		<div class="col-sm-4">
		  <input type="text" name="age" class="form-control form-control-sm" value="{{ employee.age }}">
		</div>
	  </div>
	  <div class="row mb-1">
		<label class="col-form-label">Enter Employee Salary</label>
		<div class="col-sm-4">
		  <input type="text" name="salary" class="form-control form-control-sm" value="{{ employee.salary }}">
		</div>
	  </div>
	  <div class="row mb-1">
		<label class="col-form-label">Enter Employee Address</label>
		<div class="col-sm-4">
		  <input type="text" name="address" class="form-control form-control-sm" value="{{ employee.address }}">
		</div>
	  </div>
	{% if employee.id %}
	  <div class="form-group">
		    <button type="submit" class="btn btn-primary">Update Employee</button>
	  </div>
	{% else %}
	   <div class="form-group">
		    <button type="submit" class="btn btn-primary">Create Employee</button>
	  </div>
	{% endif %}
	</form>
{% endblock %}

icress_root/templates/employee_register_app/list_emp.html
{% extends 'layout.html' %}
   {% block employee_style %}
<style>
#customers {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #4CAF50;
  color: white;
}

</style>
  {% endblock %}
  {% block title_content %}
  <title>Employee Details</title>
  {% endblock %}

{% block page_content %}
<h1>Load All Employee</h1>
<br>
<a href="/employee/employeeDetails/">Create Employee</a>
<br><br>

<table id="customers">
  <tr>
    <th>ID</th>
    <th>Employee ID</th>
    <th>Name</th>
    <th>Age</th>
	<th>Salary</th>
    <th>Address</th>
  </tr>
{% for employee in employeeFBV %}
  <tr>
    <td><a href="{% url 'employee:employee_ID' pk=employee.id %}">{{ employee.id }}</a></td>
    <td>{{ employee.eno }}</td>
    <td>{{ employee.name }}</td>
    <td>{{ employee.age }}</td>
	<td>{{ employee.salary }}</td>
    <td>{{ employee.address }}</td>
  </tr>
  {% empty %}
    <tr>
      <td>No Data</a></td>
      <td>No Data</td>
      <td>No Data</td>
      <td>No Data</td>
      <td>No Data</td>
      <td>No Data</td>
    </tr>
 {% endfor %}
</table>
{% endblock %}