icress_root/icress/urls.py
from django.contrib import admin
from django.urls import path,include
from.import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',views.home),
    path('courses/',include('courses.urls')),
    path('contactus/',views.contact),
    path('aboutus/',views.about_us),
    path('registermp/',views.employee_registration),
    path('studenthp/',include('reg_app.urls')),
    path('login_logout/',views.login_logout),
    path('dtl/',views.dtl),
    path('employee/',include('employee_register_app.urls')),
    path('studentDJF/',include('student_form_app.urls')),
    path('modelformcreate/',include('model_form_app.urls')),
    path('registersign/',include('login_registration_app.urls')),
    path('vijay/',include('VIJAY_app.urls')),
    path('Hotel/',include('Hotel_app.urls'))
]

icress_root/model_form_app/urls.py
from django . urls import path
from . import views
app_name='modelforms_app'

urlpatterns = [
    path('model_form/',views.Model_Form),
    path('emp_Update/<pk>',views.Emp_Update,name='emp_Update'),
    path('emp_Delete/<pk>',views.Emp_Delete,name='emp_Delete'),
]

icress_root/Hotel_app/models.py
from django.db import models

# Create your models here.

rooms_list = [('superior king room','superior king room'),
              ('primior king room','primior king room'),
              ('double room with double beds','double room with double beds'),
              ('primior single room','primior single room')]
class Rooms(models.Model):
    username = models.CharField(max_length=20)
    room_no = models.IntegerField()
    room_name = models.CharField(max_length=30,choices=rooms_list,default='superior king room')
    room_image = models.ImageField(upload_to='media',null=True,blank=True)
    start_date = models.DateField(auto_now=False,auto_now_add=False)
    is_available = models.BooleanField(default=True)
    no_of_dats = models.IntegerField()

    def __str__(self):
        return 'Room Number :' + str(self.room_no)

icress_root/VIJAY_app/models.py
from django.db import models

# Create your models here.

class Employee_model(models.Model):
    eno=models.IntegerField()
    name=models.CharField(max_length=100)
    age=models.IntegerField()
    salary=models.IntegerField()
    address=models.CharField(max_length=100)

icress_root/courses/admin_app/models.py
from django.db import models

# Create your models here.
class Room(models.Model):
    ROOM_CATAGERIES=(
        ('YAC' , 'AC'),
        ('NAC' , 'NON-AC'),
        ('DEL' , 'DELUXE'),
        ('KIN' , 'KING'),
        ('QUE' , 'QUEEN'),
    )
    number = models.IntegerField()
    category = models.CharField(max_length=3,choices=ROOM_CATAGERIES)
    beds = models.IntegerField()
    capacity = models.IntegerField()

    def __str__(self):
        return f'{self.number}.{self.category} with{self.beds} for {self.capacity} people'

icress_root/courses/models.py
from django.db import models

# Create your models here.

icress_root/employee_register_app/models.py
from django.db import models

# Create your models here.

class Employee(models.Model):
    eno=models.IntegerField()
    name=models.CharField(max_length=100)
    age=models.IntegerField()
    salary=models.IntegerField()
    address=models.CharField(max_length=100)

icress_root/login_registration_app/models.py
from django.db import models

# Create your models here.

icress_root/model_form_app/models.py
from django.db import models

# Create your models here.

class Employee_form(models.Model):
    eno=models.IntegerField()
    name=models.CharField(max_length=100)
    age=models.IntegerField()
    salary=models.IntegerField()
    address=models.CharField(max_length=100)

    def __str__(self):
        response = self.name + ' , ' +self.name
        return response

icress_root/reg_app/models.py
from django.db import models

# Create your models here.

class Student(models.Model):
    firstname= models.CharField(max_length=100)
    lastname=models.CharField(max_length=100)
    gender=models.CharField(max_length=100)
    contactNumber=models.IntegerField()
    emailId=models.CharField(max_length=100)
    address=models.CharField(max_length=100)
    city=models.CharField(max_length=100)
    state=models.CharField(max_length=100)
    python=models.CharField(max_length=100)
    django=models.CharField(max_length=100)
    java=models.CharField(max_length=100)
    bigdata=models.CharField(max_length=100)
    username=models.CharField(max_length=100)
    password=models.CharField(max_length=100)
    confomepassword=models.CharField(max_length=100)




class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    message = models.TextField(max_length=2000)
    def __str__(self):
        return self.name

icress_root/student_form_app/models.py
from django.db import models

# Create your models here.
class StudentDjangoForms(models.Model):
    firstname=models.CharField(max_length=100)
    lastname=models.CharField(max_length=100)
    Gender=models.CharField(max_length=100)
    ContactNumber=models.IntegerField()
    Emailid=models.EmailField(max_length=100)
    Address=models.CharField(max_length=100)
    Confirm_Emailid=models.CharField(max_length=100)
    Date_of_Birth=models.DateField(max_length=100)
    City=models.CharField(max_length=100)
    State=models.CharField(max_length=100)
    Python=models.CharField(max_length=100)
    Java=models.CharField(max_length=100)

icress_root/model_form_app/forms.py
from django import forms
from .models import Employee_form

class Employee_Forms(forms.ModelForm):
    class Meta:
        model = Employee_form
        fields='__all__'
        widgets={
            'name' : forms.TextInput(attrs={'class' : 'form-control'}),
            'eno' : forms.TextInput(attrs={'class' : 'form-control'}),
            'age' : forms.TextInput(attrs={'class' : 'form-control'}),
            'salary' : forms.TextInput(attrs={'class' : 'form-control'}),
            'address' : forms.TextInput(attrs={'class' : 'form-control'}),
        }

icress_root/model_form_app/views.py
from django.shortcuts import render,redirect
from.models import Employee_form
from .forms import Employee_Forms
# Create your views here.

def Model_Form(request):
    if request.method == 'GET':
        emp_forms=Employee_Forms()
        emp_list=Employee_form.objects.all()
        emp_dict={
           'emp_forms' : emp_forms,
           'emp_list' : emp_list
        }
        return render(request,'model_form_app/model_form.html',context=emp_dict)

    elif request.method=='POST':
        emp_forms=Employee_Forms(request.POST)
        if emp_forms.is_valid():
            emp_forms.save()
            return redirect('/modelformcreate/model_form/')


def Emp_Update(request,pk):
    if request.method=='GET':
        employee=Employee_form.objects.get(id=pk)
        emp_forms = Employee_Forms(instance=employee)
        emp_list=Employee_form.objects.all()
        emp_dict={
            'emp_forms' : emp_forms,
            'emp_list' : emp_list
        }
        return render(request,'model_form_app/model_form.html',context=emp_dict)
    elif request.method=='POST':
        emp_list = Employee_form.objects.get(id=pk)
        emp_forms = Employee_Forms(request.POST,instance=emp_list)
        if emp_forms.is_valid():
            emp_forms.save()
            return redirect('/modelformcreate/model_form/')

def Emp_Delete(request,pk):
    emp_list=Employee_form.objects.get(id=pk)
    emp_list.delete()
    return redirect('/modelformcreate/model_form/')












'''    elif request.method == 'POST':
        emp_forms=Employee_Forms(request.POST)
        if emp_forms.is_valid():
            eno=emp_forms.cleaned_data['eno']
            name=emp_forms.cleaned_data['name']
            age=emp_forms.cleaned_data['age']
            salary=emp_forms.cleaned_data['salary']
            address=emp_forms.cleaned_data['address']
            employee = Employee_form(eno=eno,name=name,age=age,salary=salary,address=address)
            employee.save()
            return redirect('/modelformcreate/model_form/')
'''
    # option :1
    # elif request.method == 'POST':
    #     eno=request.POST.get('eno')
    #     name=request.POST.get('name')
    #     age=request.POST.get('age')
    #     salary=request.POST.get('salary')
    #     address=request.POST.get('address')
    #     employee=Employee_form(eno=eno,name=name,age=age,salary=salary,address=address)
    #     employee.save()
    #     return redirect('/modelformcreate/model_form/')

icress_root/templates/model_form_app/model_form.html
{% extends 'layout.html' %}

{% block title_content %}
    <title>Employee Management - ModelForm</title>
{% endblock %}

{% block page_content %}
  <div class="container mt-5">
      <h2 class="text-center alert alert-danger">Employee Management Dashboard - ModelForm</h2>

      <div class="row">
          <div class="col-sm-4"> <!-- SECTION - 1 for displying EMPLOYEE CREATE/UPDTE FORM -->
              <!-- <h4 class="text-center alert alert-info">Update Employee</h4> -->
              <h4 class="text-center alert alert-info">Create Employee</h4>
              <form action="" method="POST">
                  {% csrf_token %}

                  {{ emp_forms.as_p }}
                  <!---
                  <div class="row mb-1">
                      <label class="col-form-label">Employee Number</label>
                      <div class="col-sm-4">
                        <input type="text" name="emp_number" class="form-control form-control-sm">
                      </div>
                  </div>

                  <div class="row mb-1">
                      <label class="col-form-label">Full Name</label>
                      <div class="col-sm-4">
                        <input type="text" name="name" class="form-control form-control-sm">
                      </div>
                  </div>

                  <div class="row mb-1">
                      <label class="col-form-label">Age</label>
                      <div class="col-sm-4">
                        <input type="text" name="age" class="form-control form-control-sm">
                      </div>
                  </div>

                  <div class="row mb-1">
                      <label class="col-form-label">Salary</label>
                      <div class="col-sm-4">
                        <input type="text" name="salary" class="form-control form-control-sm">
                      </div>
                  </div>

                  <div class="row mb-1">
                      <label class="col-form-label">Address</label>
                      <div class="col-sm-4">
                        <input type="text" name="address" class="form-control form-control-sm">
                      </div>
                  </div>

                  <div class="form-group">
                   <button type="submit" class="btn btn-primary">Update Employee</button> -->
                      <button type="submit" class="btn btn-success">Create Employee</button>
                  </div>
              </form>
          </div>

          <div class="col-sm-7 offset-1"> <!-- SECTION - 2 for Rendering Existing  EMployees -->
              <h4 class="text-center alert alert-info">List of Existing Employees</h4>

                  <table class="table table-striped table-hover">
                    <thead>
                      <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Emp No</th>
                        <th scope="col">Name</th>
                        <th scope="col">Age</th>
                        <th scope="col">Salary</th>
                        <th scope="col">Address</th>
                        <th scope="col">Action</th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for employee in emp_list %}
                      <tr>
                        <th scope="row">{{ employee.id }}</th>
                        <td>{{ employee.eno }}</td>
                        <td>{{ employee.name }}</td>
                        <td>{{ employee.age }}</td>
                        <td>{{ employee.salary }}</td>
                        <td>{{ employee.address }}</td>
                        <td>
                            <a href="{% url 'modelforms_app:emp_Update' pk=employee.id %}" class="btn btn-warning btn-sm">Edit</a>
                            <a href="{% url 'modelforms_app:emp_Delete' pk=employee.id %}" class="btn btn-danger btn-sm">Delete</a>
                        </td>
                      </tr>
                    {% empty %}
                    <tr>
                        <th scope="row">NO DATA</th>
                        <td>NO DATA</td>
                        <td>NO DATA</td>
                        <td>NO DATA</td>
                        <td>NO DATA</td>
                        <td>NO DATA</td>
                        <td>N0 ACTION</td>
                        <td>
                    {% endfor %}
                    </tbody>
                  </table>

                  <!-- <h3 class="text-center alert alert-warning">Employees Does not exist</h3> -->
          </div>
      </div>
  </div>
{% endblock %}